version: '3.1'
services:
  stats-server:
    build: ./stats/server
    image: server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm

  stats-db:
    image: postgres:15-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  ewm-service:
    build: ./service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:15-alpine
